// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node scripts/run-seed.mjs",
  },
  datasource: {
    // On utilise l'URL de Turso (ou fallback SQLite en local) pour la CLI Prisma
    url: process.env.DATABASE_URL || "file:./dev.db",
  },
});
